import { createMemo, createSignal, For, Show } from "solid-js";
import { createStore, produce } from "solid-js/store";
import { Dialog, DialogFooter } from "../Dialog";
import { SqlField } from "../SqlField";
import { createTable, scriptNote, validateColumns, type ColumnSpec, type FkSpec } from "../sql/ddl";
import { ddlCaps } from "../sql/ddlCaps";
import { emptyFk, fkSpecOf, FkEditor, type FkDraft, type RefColumn, type RefTable } from "./FkEditor";

type Row = ColumnSpec & { uid: number };

let uid = 1;
const emptyCol = (): Row => ({
  uid: uid++,
  name: "",
  type: "text",
  nullable: true,
  default: "",
  primaryKey: false,
  unique: false,
  check: "",
  comment: "",
  identity: false,
});

const IDENTITY_LABEL: Record<string, string> = {
  identity: "Ident",
  auto_increment: "Auto↑",
  rowid: "Auto↑",
  sequence: "Seq",
};
const IDENTITY_HINT: Record<string, string> = {
  identity: "GENERATED BY DEFAULT AS IDENTITY",
  auto_increment: "AUTO_INCREMENT (must be the primary key)",
  rowid: "INTEGER PRIMARY KEY AUTOINCREMENT (must be the single-column primary key)",
  sequence: "DEFAULT nextval(…) over a sequence created alongside the table",
};

/** Visual CREATE TABLE builder: per-column type / NOT NULL / default / PK / unique /
 *  check / auto-numbering / comment, table-level foreign keys and engine options, and
 *  a live SQL preview that follows the connected engine's dialect. Column rows can be
 *  reordered, duplicated and tabbed through. */
export function CreateTableForm(props: {
  schema: string;
  /** Tables the FK picker can point at (from the loaded shallow tree). */
  tables?: RefTable[];
  loadColumns?: (schema: string, table: string) => Promise<RefColumn[] | null>;
  onClose: () => void;
  onRun: (sql: string) => Promise<{ ok: boolean; error?: string }>;
  onEditAsSql: (sql: string) => void;
}) {
  const caps = ddlCaps();
  const [name, setName] = createSignal("");
  const [ifNotExists, setIfNotExists] = createSignal(false);
  const [temporary, setTemporary] = createSignal(false);
  const [comment, setComment] = createSignal("");
  const [engine, setEngine] = createSignal("InnoDB");
  const [charset, setCharset] = createSignal("");
  const [collation, setCollation] = createSignal("");
  const [cols, setCols] = createStore<Row[]>([
    {
      uid: uid++,
      name: "id",
      type: caps.dialect === "sqlite" ? "integer" : "bigint",
      nullable: false,
      default: "",
      primaryKey: true,
      unique: false,
      check: "",
      comment: "",
      identity: true,
    },
    emptyCol(),
  ]);
  const [fks, setFks] = createStore<(FkDraft & { uid: number })[]>([]);
  const [showAdvanced, setShowAdvanced] = createSignal(false);
  const [busy, setBusy] = createSignal(false);
  const [error, setError] = createSignal("");

  const update = (i: number, patch: Partial<Row>) => setCols(i, patch);
  const addRow = () => setCols(produce((c) => c.push(emptyCol())));
  const removeRow = (i: number) => setCols(produce((c) => c.splice(i, 1)));
  const duplicateRow = (i: number) =>
    setCols(
      produce((c) =>
        c.splice(i + 1, 0, { ...c[i], uid: uid++, name: `${c[i].name}_copy`, primaryKey: false, identity: false }),
      ),
    );
  const move = (i: number, by: number) =>
    setCols(
      produce((c) => {
        const j = i + by;
        if (j < 0 || j >= c.length) return;
        const [row] = c.splice(i, 1);
        c.splice(j, 0, row);
      }),
    );

  const addFk = () => setFks(produce((f) => f.push({ ...emptyFk(), uid: uid++ })));
  const removeFk = (i: number) => setFks(produce((f) => f.splice(i, 1)));

  const colNames = () => cols.filter((c) => c.name.trim()).map((c) => c.name.trim());
  const localCols = () => cols.filter((c) => c.name.trim()).map((c) => ({ name: c.name.trim(), data_type: c.type }));

  const problems = createMemo(() => {
    const out = validateColumns(cols, caps);
    if (!name().trim()) out.unshift({ level: "error" as const, message: "The table needs a name." });
    const identityCols = cols.filter((c) => c.identity);
    if (identityCols.length > 1) out.push({ level: "error" as const, message: "Only one column can auto-number." });
    if ((caps.identity === "auto_increment" || caps.identity === "rowid") && identityCols.some((c) => !c.primaryKey))
      out.push({
        level: "error" as const,
        message: `${caps.label} requires the auto-numbering column to be the primary key.`,
      });
    if (caps.identity === "rowid" && identityCols.length && cols.filter((c) => c.primaryKey).length > 1)
      out.push({ level: "error" as const, message: "SQLite's AUTOINCREMENT needs a single-column primary key." });
    return out;
  });
  const errors = () => problems().filter((p) => p.level === "error");

  const foreignKeys = createMemo(() => fks.map(fkSpecOf).filter((f): f is FkSpec => !!f));

  const sql = createMemo(() =>
    errors().length
      ? ""
      : createTable({
          schema: props.schema,
          name: name().trim(),
          columns: cols.map((c) => ({ ...c })),
          ifNotExists: ifNotExists(),
          temporary: temporary(),
          comment: comment(),
          foreignKeys: foreignKeys(),
          options: caps.tableOptions ? { engine: engine(), charset: charset(), collation: collation() } : undefined,
        }),
  );
  const note = createMemo(() => (sql() ? scriptNote(sql(), caps) : ""));

  const apply = async () => {
    if (!sql()) return;
    setBusy(true);
    setError("");
    const r = await props.onRun(sql());
    setBusy(false);
    if (r.ok) props.onClose();
    else setError(r.error ?? "failed");
  };

  return (
    <Dialog
      title={`Create table · ${props.schema}`}
      onClose={props.onClose}
      width={Math.min(window.innerWidth - 80, 1020)}
    >
      <div class="modify-head">
        <label>
          Table name
          <input value={name()} onInput={(e) => setName(e.currentTarget.value)} placeholder="table_name" autofocus />
        </label>
        <Show when={caps.comments !== "none"}>
          <label>
            Comment
            <input value={comment()} onInput={(e) => setComment(e.currentTarget.value)} placeholder="(none)" />
          </label>
        </Show>
      </div>

      <div class="col-builder">
        <div class="col-builder-head create-row">
          <span class="cb-move" />
          <span>Name</span>
          <span>Type</span>
          <span class="cb-flag" title="Nullable">Null</span>
          <span class="cb-flag" title="Primary key">PK</span>
          <span class="cb-flag" title="Unique">Uq</span>
          <span class="cb-flag" title={IDENTITY_HINT[caps.identity]}>{IDENTITY_LABEL[caps.identity]}</span>
          <span>Default</span>
          <span class="cb-x" />
        </div>
        <For each={cols}>
          {(c, i) => (
            <div class="col-builder-row create-row">
              <span class="cb-move">
                <button class="icon" title="Move up" disabled={i() === 0} onClick={() => move(i(), -1)}>↑</button>
                <button class="icon" title="Move down" disabled={i() === cols.length - 1} onClick={() => move(i(), 1)}>↓</button>
              </span>
              <input value={c.name} onInput={(e) => update(i(), { name: e.currentTarget.value })} placeholder="name" />
              <SqlField value={c.type} typesOnly onChange={(v) => update(i(), { type: v })} placeholder="type" />
              <input
                class="cb-flag"
                type="checkbox"
                title="Nullable"
                checked={c.nullable}
                onChange={(e) => update(i(), { nullable: e.currentTarget.checked })}
              />
              <input
                class="cb-flag"
                type="checkbox"
                title="Primary key"
                checked={c.primaryKey}
                onChange={(e) =>
                  update(i(), { primaryKey: e.currentTarget.checked, nullable: e.currentTarget.checked ? false : c.nullable })
                }
              />
              <input
                class="cb-flag"
                type="checkbox"
                title="Unique"
                checked={c.unique}
                onChange={(e) => update(i(), { unique: e.currentTarget.checked })}
              />
              <input
                class="cb-flag"
                type="checkbox"
                title={IDENTITY_HINT[caps.identity]}
                checked={c.identity}
                onChange={(e) => update(i(), { identity: e.currentTarget.checked })}
              />
              <SqlField
                value={c.default}
                columns={colNames()}
                onChange={(v) => update(i(), { default: v })}
                placeholder="(none)"
              />
              <span class="cb-x">
                <button class="icon" title="Duplicate column" onClick={() => duplicateRow(i())}>⧉</button>
                <button class="icon" title="Remove" onClick={() => removeRow(i())}>✕</button>
              </span>
            </div>
          )}
        </For>
        <button class="ghost full" onClick={addRow}>＋ Add column</button>
      </div>

      <button class="ghost full" onClick={() => setShowAdvanced(!showAdvanced())}>
        {showAdvanced() ? "▾" : "▸"} Checks, comments, foreign keys{caps.tableOptions ? " and table options" : ""}
      </button>
      <Show when={showAdvanced()}>
        <div class="field-label">Per-column check and comment</div>
        <div class="col-builder">
          <For each={cols}>
            {(c, i) => (
              <div class="col-builder-row extra-row">
                <span class="mono">{c.name || "(unnamed)"}</span>
                <SqlField
                  value={c.check ?? ""}
                  columns={colNames()}
                  onChange={(v) => update(i(), { check: v })}
                  placeholder="CHECK expression (none)"
                />
                <Show when={caps.comments !== "none"} fallback={<span class="muted-hint">{caps.label} has no comments</span>}>
                  <input
                    value={c.comment ?? ""}
                    onInput={(e) => update(i(), { comment: e.currentTarget.value })}
                    placeholder="comment (none)"
                  />
                </Show>
              </div>
            )}
          </For>
        </div>

        <Show when={caps.inlineForeignKey && props.tables}>
          <div class="field-label">Foreign keys</div>
          <For each={fks}>
            {(f, i) => (
              <div class="fk-block">
                <FkEditor
                  localColumns={localCols()}
                  tables={props.tables ?? []}
                  loadColumns={props.loadColumns}
                  value={f}
                  onChange={(patch) => setFks(i(), patch)}
                />
                <button class="ghost" onClick={() => removeFk(i())}>Remove foreign key</button>
              </div>
            )}
          </For>
          <button class="ghost full" onClick={addFk}>＋ Add foreign key</button>
        </Show>

        <div class="seg">
          <Show when={caps.ifNotExists}>
            <label class="checkbox">
              <input type="checkbox" checked={ifNotExists()} onChange={(e) => setIfNotExists(e.currentTarget.checked)} />
              IF NOT EXISTS
            </label>
          </Show>
          <Show when={caps.temporary}>
            <label class="checkbox">
              <input type="checkbox" checked={temporary()} onChange={(e) => setTemporary(e.currentTarget.checked)} />
              TEMPORARY
            </label>
          </Show>
        </div>

        <Show when={caps.tableOptions}>
          <div class="field-label">Table options</div>
          <div class="seg">
            <label>
              Engine
              <input value={engine()} onInput={(e) => setEngine(e.currentTarget.value)} placeholder="InnoDB" />
            </label>
            <label>
              Charset
              <input value={charset()} onInput={(e) => setCharset(e.currentTarget.value)} placeholder="utf8mb4" />
            </label>
            <label>
              Collation
              <input value={collation()} onInput={(e) => setCollation(e.currentTarget.value)} placeholder="(server default)" />
            </label>
          </div>
        </Show>
      </Show>

      <Show when={errors().length}>
        <div class="error">{errors()[0].message}</div>
      </Show>
      <Show when={note()}>
        <div class="muted-hint script-note">{note()}</div>
      </Show>
      <DialogFooter
        sql={sql()}
        error={error()}
        busy={busy()}
        disabled={!sql()}
        primaryLabel="Create table"
        onPrimary={apply}
        onEditAsSql={() => props.onEditAsSql(sql())}
        onCancel={props.onClose}
      />
    </Dialog>
  );
}
