// Pure SQL builders. Each returns a single statement, or — where noted — a small
// `;\n`-joined script (the run path splits on `;` and executes the whole thing in one
// transaction, except on MySQL where every DDL statement implicitly commits).
// Quoting via ident.ts; per-engine syntax facts via ddlCaps.ts.
//
// Every builder is dialect-aware through `ddlCaps()`: what an engine can express is
// declared once in `sql/ddlCaps.ts`, never re-derived from `sqlDialect() === "…"`
// checks sprinkled through the emitters.

import { ident, qualify, qualifyIn, lit, mysqlNoBackslashEscapes, sqlDialect } from "./ident";
import { ddlCaps, type DdlCaps } from "./ddlCaps";

/** Suffix for the scratch table a SQLite rebuild creates before swapping it in. */
export const REBUILD_SUFFIX = "__tusk_rebuild";

/**
 * A script produced by `rebuildTable` — the one DDL shape that must run with SQLite's
 * foreign-key enforcement suspended, and therefore with `PRAGMA foreign_keys=OFF/ON`
 * issued as separate IDLE statements around it (the pragma is a silent no-op inside the
 * transaction the script itself runs in). Recognised by the scratch table's reserved
 * suffix, which only this builder emits.
 */
export function isSqliteRebuild(sql: string, dialect = sqlDialect()): boolean {
  return dialect === "sqlite" && sql.includes(REBUILD_SUFFIX);
}

export type ColumnSpec = {
  name: string;
  type: string;
  nullable: boolean;
  default: string; // raw SQL expression; "" = none
  primaryKey?: boolean;
  unique?: boolean;
  check?: string; // raw boolean expression; "" = none
  comment?: string;
  collate?: string;
  /** Auto-numbering. Rendered per engine: PG `GENERATED BY DEFAULT AS IDENTITY`,
   *  MySQL `AUTO_INCREMENT`, SQLite `INTEGER PRIMARY KEY AUTOINCREMENT`, DuckDB a
   *  `DEFAULT nextval('…')` over a sequence created by `createTable`. */
  identity?: boolean;
  /** A generated column's whole clause, verbatim from the catalog
   *  (`GENERATED ALWAYS AS (a + b) STORED`). It replaces the default/PK/UNIQUE part of
   *  the definition: a generated column has no default and cannot be assigned. */
  generated?: string;
  /** MySQL `ON UPDATE CURRENT_TIMESTAMP(…)` — part of the column definition, so a
   *  MODIFY that omits it silently removes the auto-update behaviour. */
  onUpdate?: string;
};

/** MySQL's inline COMMENT option takes a plain string literal token, so the hex form
 *  `lit()` uses for MySQL values (`_utf8mb4 X'…'`) is not accepted there. Quotes are
 *  always doubled; backslashes are doubled ONLY when the session treats them as escape
 *  characters — doubling under NO_BACKSLASH_ESCAPES would store two of them, and not
 *  doubling under the default mode turns `\n` in a comment into a newline. */
export function mysqlTextLiteral(s: string): string {
  const escaped = mysqlNoBackslashEscapes() ? s : s.replace(/\\/g, "\\\\");
  return `'${escaped.replace(/'/g, "''")}'`;
}

/** Comment text as a literal for the active dialect's COMMENT syntax. */
const commentLit = (s: string, caps: DdlCaps): string =>
  caps.dialect === "mysql" ? mysqlTextLiteral(s) : lit(s);

/** A single column definition for CREATE TABLE / ADD COLUMN. `inlinePk` renders the
 *  column's PRIMARY KEY inline (single-column keys); composite keys use a table
 *  constraint instead and pass `false`. */
export function columnDef(c: ColumnSpec, caps: DdlCaps = ddlCaps(), inlinePk = true): string {
  const type = c.type.trim();
  const parts: string[] = [ident(c.name), type];
  const pk = !!c.primaryKey && inlinePk;
  const def = c.default.trim();

  if (caps.dialect === "mysql") {
    // MySQL's column_definition grammar is order-sensitive:
    // data_type [NOT NULL|NULL] [DEFAULT …] [ON UPDATE …] [AUTO_INCREMENT] [UNIQUE]
    // [PRIMARY KEY] [COMMENT …]
    if (c.collate?.trim()) parts.push(`COLLATE ${c.collate.trim()}`);
    if (c.generated?.trim()) {
      // A generated column takes its expression instead of DEFAULT/AUTO_INCREMENT.
      parts.push(c.generated.trim());
      if (!c.nullable) parts.push("NOT NULL");
      if (c.comment?.trim()) parts.push(`COMMENT ${mysqlTextLiteral(c.comment.trim())}`);
      return parts.join(" ");
    }
    if (!c.nullable || pk || c.identity) parts.push("NOT NULL");
    if (def) parts.push(`DEFAULT ${def}`);
    if (c.onUpdate?.trim()) parts.push(c.onUpdate.trim());
    if (c.identity) parts.push("AUTO_INCREMENT");
    if (c.unique && !pk) parts.push("UNIQUE");
    if (pk) parts.push("PRIMARY KEY");
    if (c.check?.trim()) parts.push(`CHECK (${c.check.trim()})`);
    if (c.comment?.trim()) parts.push(`COMMENT ${mysqlTextLiteral(c.comment.trim())}`);
    return parts.join(" ");
  }

  if (caps.dialect === "sqlite") {
    if (c.generated?.trim()) {
      // Generated columns carry their expression, never a default or a key.
      if (c.collate?.trim()) parts.push(`COLLATE ${c.collate.trim()}`);
      parts.push(c.generated.trim());
      if (!c.nullable) parts.push("NOT NULL");
      if (c.check?.trim()) parts.push(`CHECK (${c.check.trim()})`);
      return parts.join(" ");
    }
    // The rowid alias: only `INTEGER PRIMARY KEY [AUTOINCREMENT]` auto-numbers.
    if (c.identity && pk) {
      parts[1] = "INTEGER";
      parts.push("PRIMARY KEY", "AUTOINCREMENT");
      if (c.collate?.trim()) parts.push(`COLLATE ${c.collate.trim()}`);
      if (c.check?.trim()) parts.push(`CHECK (${c.check.trim()})`);
      return parts.join(" ");
    }
    if (pk) parts.push("PRIMARY KEY");
    if (!c.nullable && !pk) parts.push("NOT NULL");
    if (def) parts.push(`DEFAULT ${def}`);
    if (c.unique && !pk) parts.push("UNIQUE");
    if (c.collate?.trim()) parts.push(`COLLATE ${c.collate.trim()}`);
    if (c.check?.trim()) parts.push(`CHECK (${c.check.trim()})`);
    return parts.join(" ");
  }

  // Postgres / DuckDB. DEFAULT before NOT NULL/PRIMARY KEY (historical form, kept so
  // the emitted text stays stable); identity replaces an explicit default on PG.
  if (c.collate?.trim()) parts.push(`COLLATE ${ident(c.collate.trim())}`);
  if (c.identity && caps.identity === "identity") parts.push("GENERATED BY DEFAULT AS IDENTITY");
  else if (def) parts.push(`DEFAULT ${def}`);
  if (pk) parts.push("PRIMARY KEY");
  else if (!c.nullable) parts.push("NOT NULL");
  if (c.unique && !pk) parts.push("UNIQUE");
  if (c.check?.trim()) parts.push(`CHECK (${c.check.trim()})`);
  return parts.join(" ");
}

/** DuckDB ADD COLUMN can't carry constraints, so split into a plain add + follow-up
 *  ALTERs (DuckDB takes one ALTER action per statement). NOTE: no backfill — DuckDB
 *  refuses `SET NOT NULL` with an outstanding UPDATE in the same transaction (the run
 *  path is transactional), and on a populated table the SET NOT NULL itself fails with
 *  a clear "NOT NULL constraint failed" — so adding a NOT NULL column works when the
 *  table is empty (schema design) and otherwise surfaces DuckDB's real limitation. */
function duckAddColumn(q: string, c: ColumnSpec): string[] {
  const col = ident(c.name);
  const out = [`ALTER TABLE ${q} ADD COLUMN ${col} ${c.type.trim()}`];
  if (c.default.trim()) out.push(`ALTER TABLE ${q} ALTER COLUMN ${col} SET DEFAULT ${c.default.trim()}`);
  if (c.primaryKey) out.push(`ALTER TABLE ${q} ADD PRIMARY KEY (${col})`); // implies NOT NULL
  else if (!c.nullable) out.push(`ALTER TABLE ${q} ALTER COLUMN ${col} SET NOT NULL`);
  return out;
}

/** Statements adding one column, per engine. */
function addColumnStatements(q: string, c: ColumnSpec, caps: DdlCaps): string[] {
  if (caps.dialect === "duckdb") return duckAddColumn(q, c);
  // SQLite ADD COLUMN can't take PRIMARY KEY / UNIQUE (documented restriction), and a
  // NOT NULL add needs a non-null default; emit what SQLite accepts and let the engine
  // reject the rest with its own message.
  const spec = caps.dialect === "sqlite" ? { ...c, primaryKey: false, unique: false } : c;
  const out = [`ALTER TABLE ${q} ADD COLUMN ${columnDef(spec, caps)}`];
  if (caps.comments === "standard" && c.comment?.trim())
    out.push(`COMMENT ON COLUMN ${q}.${ident(c.name)} IS ${commentLit(c.comment.trim(), caps)}`);
  return out;
}

export function addColumn(schema: string, table: string, c: ColumnSpec): string {
  return addColumnStatements(qualify(schema, table), c, ddlCaps()).join(";\n");
}

export function dropColumn(schema: string, table: string, name: string, cascade: boolean): string {
  const caps = ddlCaps();
  const c = cascade && caps.cascade ? " CASCADE" : "";
  return `ALTER TABLE ${qualify(schema, table)} DROP COLUMN ${ident(name)}${c}`;
}

/** Combined ALTER COLUMN edit: type / default / not-null in one statement, plus a
 *  separate RENAME (Postgres forbids RENAME in a multi-action ALTER). Returns the
 *  joined script (`;`-separated when a rename is included).
 *
 *  `target` is the column's COMPLETE resulting definition and is required on engines
 *  whose type change rewrites the whole column (MySQL `MODIFY COLUMN`) — without it a
 *  type change there would silently drop NOT NULL / DEFAULT / AUTO_INCREMENT / COMMENT. */
export function editColumn(
  schema: string,
  table: string,
  col: string,
  e: {
    newName?: string;
    type?: string; // new type, "" = unchanged
    using?: string; // USING expr for the type cast
    setDefault?: string | null; // string = SET DEFAULT, null = DROP DEFAULT, undefined = unchanged
    notNull?: boolean; // undefined = unchanged
    comment?: string | null; // string = set, null = drop, undefined = unchanged
    target?: ColumnSpec; // full resulting definition (MySQL MODIFY / SQLite rebuild)
  },
): string {
  const caps = ddlCaps();
  const q = qualify(schema, table);
  const stmts: string[] = [];

  if (caps.changeType === "rebuild") {
    // SQLite's ALTER TABLE has no ALTER COLUMN at all: the only edit expressible here
    // is the rename. Everything else needs the Modify-table rebuild, so emit nothing
    // for it rather than SQL the engine cannot parse (the dialog says as much).
    if (e.newName && e.newName.trim() && e.newName !== col)
      stmts.push(`ALTER TABLE ${q} RENAME COLUMN ${ident(col)} TO ${ident(e.newName.trim())}`);
    return stmts.join(";\n");
  }

  if (caps.changeType === "modify") {
    // MySQL: one MODIFY carries type + nullability + default + comment together.
    const rewrite = (e.type && e.type.trim()) || e.notNull !== undefined || e.comment !== undefined;
    if (rewrite && e.target) {
      const spec: ColumnSpec = {
        ...e.target,
        name: col,
        type: (e.type && e.type.trim()) || e.target.type,
        nullable: e.notNull === undefined ? e.target.nullable : !e.notNull,
        comment: e.comment === undefined ? e.target.comment : (e.comment ?? ""),
      };
      stmts.push(`ALTER TABLE ${q} MODIFY COLUMN ${columnDef(spec, caps, false)}`);
    } else if (rewrite) {
      // No target supplied — fall back to the narrowest legal MySQL action we can.
      if (e.notNull !== undefined)
        stmts.push(`ALTER TABLE ${q} MODIFY COLUMN ${ident(col)} ${(e.type ?? "").trim()}${e.notNull ? " NOT NULL" : ""}`);
    }
    if (e.setDefault !== undefined) {
      stmts.push(
        e.setDefault === null || !e.setDefault.trim()
          ? `ALTER TABLE ${q} ALTER COLUMN ${ident(col)} DROP DEFAULT`
          : `ALTER TABLE ${q} ALTER COLUMN ${ident(col)} SET DEFAULT ${e.setDefault.trim()}`,
      );
    }
    if (e.newName && e.newName.trim() && e.newName !== col)
      stmts.push(`ALTER TABLE ${q} RENAME COLUMN ${ident(col)} TO ${ident(e.newName.trim())}`);
    return stmts.join(";\n");
  }

  const actions: string[] = [];
  if (e.type && e.type.trim()) {
    const using = caps.usingClause && e.using && e.using.trim() ? ` USING ${e.using.trim()}` : "";
    actions.push(`ALTER COLUMN ${ident(col)} TYPE ${e.type.trim()}${using}`);
  }
  if (e.notNull !== undefined) {
    actions.push(`ALTER COLUMN ${ident(col)} ${e.notNull ? "SET" : "DROP"} NOT NULL`);
  }
  if (e.setDefault !== undefined) {
    actions.push(
      e.setDefault === null || !e.setDefault.trim()
        ? `ALTER COLUMN ${ident(col)} DROP DEFAULT`
        : `ALTER COLUMN ${ident(col)} SET DEFAULT ${e.setDefault.trim()}`,
    );
  }
  // DuckDB allows only one ALTER action per statement; Postgres takes them comma-joined.
  if (actions.length) {
    if (caps.multiActionAlter) stmts.push(`ALTER TABLE ${q} ${actions.join(", ")}`);
    else for (const a of actions) stmts.push(`ALTER TABLE ${q} ${a}`);
  }
  if (e.comment !== undefined && caps.comments === "standard")
    stmts.push(`COMMENT ON COLUMN ${q}.${ident(col)} IS ${e.comment === null || e.comment === "" ? "NULL" : commentLit(e.comment, caps)}`);
  if (e.newName && e.newName.trim() && e.newName !== col) {
    stmts.push(`ALTER TABLE ${q} RENAME COLUMN ${ident(col)} TO ${ident(e.newName.trim())}`);
  }
  return stmts.join(";\n");
}

// --- table-level constraint clauses (shared by CREATE TABLE and ALTER) -------

export type FkSpec = {
  columns: string[];
  refSchema: string;
  refTable: string;
  refColumns: string[];
  onDelete?: string;
  onUpdate?: string;
  name?: string;
  deferrable?: boolean;
  initiallyDeferred?: boolean;
};

/** `FOREIGN KEY (…) REFERENCES … (…) [ON DELETE …] [ON UPDATE …] [DEFERRABLE …]` */
export function fkClause(fk: FkSpec, caps: DdlCaps = ddlCaps()): string {
  const ref = caps.fkRefQualified && fk.refSchema ? qualify(fk.refSchema, fk.refTable) : ident(fk.refTable);
  let s =
    `FOREIGN KEY (${fk.columns.map(ident).join(", ")}) ` +
    `REFERENCES ${ref} (${fk.refColumns.map(ident).join(", ")})`;
  if (fk.onDelete) s += ` ON DELETE ${fk.onDelete}`;
  if (fk.onUpdate && caps.onUpdateAction) s += ` ON UPDATE ${fk.onUpdate}`;
  if (fk.deferrable && caps.deferrable)
    s += fk.initiallyDeferred ? " DEFERRABLE INITIALLY DEFERRED" : " DEFERRABLE";
  return s;
}

const named = (name: string | undefined): string =>
  name && name.trim() ? `CONSTRAINT ${ident(name.trim())} ` : "";

// --- CREATE TABLE -----------------------------------------------------------

export type TableConstraintSpec = {
  uniques: { name?: string; columns: string[] }[];
  checks: { name?: string; expr: string }[];
  foreignKeys: FkSpec[];
};

export type MySqlTableOptions = { engine?: string; charset?: string; collation?: string };

/** MySQL's ENGINE / CHARSET / COLLATE take a bare grammar token. */
const OPTION_TOKEN = /^[A-Za-z0-9_]+$/;

/** Problems with the MySQL table options, for the Create-table dialog. */
export function validateTableOptions(o: MySqlTableOptions | undefined): DdlProblem[] {
  if (!o) return [];
  const out: DdlProblem[] = [];
  for (const [label, v] of [
    ["Engine", o.engine],
    ["Charset", o.charset],
    ["Collation", o.collation],
  ] as const) {
    if (v && v.trim() && !OPTION_TOKEN.test(v.trim()))
      out.push({ level: "error", message: `${label} must be a plain name (letters, digits and _).` });
  }
  return out;
}

export type CreateTableSpec = {
  schema: string;
  name: string;
  columns: ColumnSpec[];
  ifNotExists?: boolean;
  temporary?: boolean;
  comment?: string;
  uniques?: { name?: string; columns: string[] }[];
  checks?: { name?: string; expr: string }[];
  foreignKeys?: FkSpec[];
  /** Verbatim table-constraint clauses (e.g. `UNIQUE ("a")`, `CHECK (x > 0)`), used by
   *  the SQLite rebuild to carry the table's existing constraints across unchanged. */
  rawConstraints?: string[];
  options?: MySqlTableOptions;
  /** Verbatim table options appended after the closing paren — SQLite's
   *  `WITHOUT ROWID` / `STRICT`, carried across by a rebuild. */
  rawOptions?: string;
};

export function createTable(t: CreateTableSpec): string {
  const caps = ddlCaps();
  const cols = t.columns.filter((c) => c.name.trim() && c.type.trim());
  const pks = cols.filter((c) => c.primaryKey);
  // A single-column key renders inline; a composite one becomes a table constraint.
  // SQLite's AUTOINCREMENT rowid alias is only legal inline, so it always wins.
  const inlinePk = pks.length === 1;
  const pre: string[] = [];
  const post: string[] = [];

  const rendered = cols.map((c) => {
    if (caps.identity === "sequence" && c.identity) {
      // DuckDB has no identity clause — a sequence supplies the default.
      const seq = `${t.name}_${c.name}_seq`;
      pre.push(`CREATE SEQUENCE ${qualify(t.schema, seq)}`);
      return columnDef({ ...c, identity: false, default: `nextval(${lit(qualify(t.schema, seq))})` }, caps, inlinePk);
    }
    return columnDef(c, caps, inlinePk);
  });

  const lines = rendered.map((s) => "  " + s);
  if (pks.length && !inlinePk) lines.push(`  PRIMARY KEY (${pks.map((c) => ident(c.name)).join(", ")})`);
  for (const u of t.uniques ?? []) if (u.columns.length) lines.push(`  ${named(u.name)}UNIQUE (${u.columns.map(ident).join(", ")})`);
  for (const c of t.checks ?? []) if (c.expr.trim()) lines.push(`  ${named(c.name)}CHECK (${c.expr.trim()})`);
  for (const fk of t.foreignKeys ?? [])
    if (fk.columns.length && fk.refTable && fk.refColumns.length) lines.push(`  ${named(fk.name)}${fkClause(fk, caps)}`);
  for (const raw of t.rawConstraints ?? []) if (raw.trim()) lines.push(`  ${raw.trim()}`);

  const ine = t.ifNotExists && caps.ifNotExists ? "IF NOT EXISTS " : "";
  const temp = t.temporary && caps.temporary ? "TEMPORARY " : "";
  const q = caps.schemas ? qualify(t.schema, t.name) : ident(t.name);
  let create = `CREATE ${temp}TABLE ${ine}${q} (\n${lines.join(",\n")}\n)`;

  if (caps.tableOptions && t.options) {
    // ENGINE/CHARSET/COLLATE are bare grammar tokens, not identifiers or literals —
    // there is nothing to quote, so anything that isn't a plain token is dropped here
    // rather than interpolated. `validateTableOptions` reports it in the dialog.
    const opts: string[] = [];
    const tok = (v: string | undefined) => (v && OPTION_TOKEN.test(v.trim()) ? v.trim() : "");
    if (tok(t.options.engine)) opts.push(`ENGINE=${tok(t.options.engine)}`);
    if (tok(t.options.charset)) opts.push(`DEFAULT CHARSET=${tok(t.options.charset)}`);
    if (tok(t.options.collation)) opts.push(`COLLATE=${tok(t.options.collation)}`);
    if (t.comment?.trim()) opts.push(`COMMENT=${mysqlTextLiteral(t.comment.trim())}`);
    if (opts.length) create += " " + opts.join(" ");
  } else if (caps.comments === "inline" && t.comment?.trim()) {
    create += ` COMMENT=${mysqlTextLiteral(t.comment.trim())}`;
  }
  if (t.rawOptions?.trim()) create += ` ${t.rawOptions.trim()}`;

  if (caps.comments === "standard") {
    if (t.comment?.trim()) post.push(`COMMENT ON TABLE ${q} IS ${commentLit(t.comment.trim(), caps)}`);
    for (const c of cols)
      if (c.comment?.trim()) post.push(`COMMENT ON COLUMN ${q}.${ident(c.name)} IS ${commentLit(c.comment.trim(), caps)}`);
  }
  return [...pre, create, ...post].join(";\n");
}

// --- SQLite table rebuild ---------------------------------------------------

export type RebuildSpec = {
  schema: string;
  table: string;
  newName: string;
  /** Target columns in order. `source` is the ORIGINAL column name the data comes
   *  from (null for a newly added column, which is left to its default). */
  columns: { source: string | null; spec: ColumnSpec }[];
  uniques?: { name?: string; columns: string[] }[];
  checks?: { name?: string; expr: string }[];
  foreignKeys?: FkSpec[];
  /** Existing table-constraint clauses to carry across verbatim. */
  constraintClauses?: string[];
  /** Full `CREATE INDEX …` statements to replay after the swap (the originals go
   *  away with the dropped table). */
  indexes?: string[];
  /** Full `CREATE TRIGGER …` statements to replay — a table's triggers are dropped
   *  with it, and SQLite keeps their whole text in `sqlite_master`. */
  triggers?: string[];
  /** `WITHOUT ROWID` / `STRICT`, carried onto the rebuilt table. */
  tableOptions?: string;
};

/** SQLite's documented table rebuild: create the new shape, copy the rows, drop the
 *  original, rename the replacement into its place, then recreate its indexes and
 *  triggers. Used for every change SQLite's ALTER TABLE cannot express (type changes,
 *  NOT NULL, defaults, constraints, dropping a key column, reordering columns).
 *
 *  Runs inside the app-owned transaction, so it is all-or-nothing. That is also why the
 *  script itself carries no `PRAGMA foreign_keys`: Tusk's SQLite build enforces foreign
 *  keys, `DROP TABLE` performs an implicit `DELETE FROM` that orphans a referencing
 *  child row ("FOREIGN KEY constraint failed"), and neither pragma can fix that from in
 *  here — `foreign_keys` is a silent no-op inside a transaction, and
 *  `defer_foreign_keys` only moves the same failure to the COMMIT (renaming the
 *  replacement in does not decrement the deferred violation counter). Retiring the
 *  original by rename first does not help either: with foreign keys on, SQLite rewrites
 *  other tables' `REFERENCES` clauses to follow the rename even under
 *  `legacy_alter_table`. So `App.runDDL` brackets the whole run with
 *  `PRAGMA foreign_keys=OFF/ON` as separate idle statements — see `isSqliteRebuild`.
 *
 *  `PRAGMA legacy_alter_table` wraps the swap, exactly as SQLite's own 12-step recipe
 *  prescribes: since 3.25 a plain `RENAME TO` re-parses every entry in `sqlite_schema`,
 *  so with a view or another table's trigger mentioning the just-dropped original the
 *  rename aborts with "error in view …: no such table" and the whole edit rolls back. */
export function rebuildTable(s: RebuildSpec): string {
  const src = qualify(s.schema, s.table);
  const tmpName = `${s.table}${REBUILD_SUFFIX}`;
  const tmp = qualify(s.schema, tmpName);
  const finalName = s.newName.trim() || s.table;
  const cols = s.columns.filter((c) => c.spec.name.trim() && c.spec.type.trim());

  const create = createTable({
    schema: s.schema,
    name: tmpName,
    columns: cols.map((c) => c.spec),
    uniques: s.uniques,
    checks: s.checks,
    foreignKeys: s.foreignKeys,
    rawConstraints: s.constraintClauses,
    rawOptions: s.tableOptions,
  });

  // A generated column has no stored value to copy — SQLite recomputes it.
  const copied = cols.filter((c) => c.source && !c.spec.generated?.trim());
  const stmts: string[] = [create];
  if (copied.length)
    stmts.push(
      `INSERT INTO ${tmp} (${copied.map((c) => ident(c.spec.name)).join(", ")})\n` +
        `SELECT ${copied.map((c) => ident(c.source!)).join(", ")} FROM ${src}`,
    );
  stmts.push(`PRAGMA legacy_alter_table=1`);
  stmts.push(`DROP TABLE ${src}`);
  stmts.push(`ALTER TABLE ${tmp} RENAME TO ${ident(finalName)}`);
  stmts.push(`PRAGMA legacy_alter_table=0`);
  for (const ix of s.indexes ?? []) if (ix.trim()) stmts.push(ix.trim().replace(/;\s*$/, ""));
  for (const tg of s.triggers ?? []) if (tg.trim()) stmts.push(tg.trim().replace(/;\s*$/, ""));
  // The banner is a leading COMMENT, not a statement — joining it with `;` would put
  // the separator inside the comment line. `script.rs`'s `effective_start` skips
  // leading comments, so the script still classifies as CREATE TABLE.
  return `-- SQLite can't ALTER ${src} in place — rebuilding it (create → copy → drop → rename).\n${stmts.join(";\n")}`;
}

// --- MODIFY TABLE diff ------------------------------------------------------

export type DiffColumn = {
  orig: {
    name: string;
    type: string;
    nullable: boolean;
    default: string;
    comment: string;
    identity?: boolean;
  } | null;
  name: string;
  type: string;
  nullable: boolean;
  default: string;
  comment: string;
  isPk: boolean;
  origPk: boolean;
  dropped: boolean;
  identity?: boolean;
  /** Carried across a rebuild verbatim — the catalog is the only place they exist. */
  collate?: string;
  check?: string;
  generated?: string;
  onUpdate?: string;
};

/** One existing object that a rebuild has to recreate, with the columns it names. An
 *  empty `columns` list means "unknown", never "none". */
export type Dependent = {
  name: string;
  kind: "index" | "constraint" | "trigger";
  columns: string[];
};
export type TableDiffSpec = {
  schema: string;
  table: string;
  newName: string;
  newSchema?: string; // PG: ALTER TABLE … SET SCHEMA
  newComment: string;
  origComment: string;
  pkName?: string;
  columns: DiffColumn[];
  dropIndexes: string[];
  dropConstraints: string[];
  /** Kinds of the dropped constraints, keyed by name — MySQL drops each kind with a
   *  different action (`DROP FOREIGN KEY` / `DROP INDEX` / `DROP PRIMARY KEY`). */
  constraintKinds?: Record<string, string>;
  /** New constraints added in the dialog. */
  addUniques?: { name?: string; columns: string[] }[];
  addChecks?: { name?: string; expr: string }[];
  addForeignKeys?: FkSpec[];
  /** Full `CREATE INDEX …` statements for indexes that must survive a SQLite rebuild. */
  keepIndexes?: string[];
  /** Existing table-constraint clauses (UNIQUE/CHECK/FOREIGN KEY, NOT the primary key —
   *  that comes from the column list) that must survive a SQLite rebuild. */
  keepConstraints?: string[];
  /** Full `CREATE TRIGGER …` statements to replay after a SQLite rebuild. */
  keepTriggers?: string[];
  /** Verbatim table options a rebuild must keep (SQLite `WITHOUT ROWID` / `STRICT`). */
  tableOptions?: string;
  /** The original column order, to detect a reorder (only a rebuild can express one). */
  origOrder?: string[];
  /** The SURVIVING indexes/constraints/triggers and the columns they name. A rebuild
   *  recreates these verbatim, so a dropped or renamed column they reference has to be
   *  refused rather than emitted as a script that fails half-way. */
  dependents?: Dependent[];
  /** False when the engine stores its definition as text and Tusk could not read it. */
  definitionRead?: boolean;
};

const specOf = (r: DiffColumn): ColumnSpec => ({
  name: r.name.trim() || r.orig?.name || "",
  type: r.type.trim() || r.orig?.type || "",
  nullable: r.nullable,
  default: r.default,
  comment: r.comment,
  identity: r.identity ?? r.orig?.identity,
  collate: r.collate,
  check: r.check,
  generated: r.generated,
  onUpdate: r.onUpdate,
});

/** The indexes a dialog may offer to drop on their own: one that BACKS a constraint is
 *  the constraint's, and dropping it twice (once per list) fails the second time — on
 *  MySQL after the first drop has already committed. */
export function droppableIndexes<T extends { name: string }>(
  indexes: T[],
  constraints: { name: string }[],
): T[] {
  const backed = new Set(constraints.map((c) => c.name));
  return indexes.filter((ix) => !backed.has(ix.name));
}

/** Columns covered by a unique index, taken from the index's key-column DATA. An index
 *  whose columns are unknown contributes nothing: guessing them by scanning the rendered
 *  `def` for a column name matches every name that is a substring of another. */
export function uniqueIndexColumns(indexes: { unique: boolean; columns?: string[] }[]): string[] {
  return indexes.filter((ix) => ix.unique).flatMap((ix) => ix.columns ?? []);
}

/** Does this SQL text name that identifier? A whole-token match (quotes and dots are
 *  not identifier characters, so `"col"` and `t.col` both count) — deliberately NOT a
 *  substring test, which would match `user` inside `user_id`. Used to decide whether a
 *  recreated trigger still depends on a column the diff is about to drop, so a false
 *  positive costs a refusal and a false negative costs a broken script. */
export function mentionsIdentifier(sql: string, name: string): boolean {
  if (!name) return false;
  const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`(^|[^A-Za-z0-9_$])${esc}([^A-Za-z0-9_$]|$)`, "i").test(sql);
}

/** Case-insensitive name membership (every engine that rebuilds folds case). */
const namesInclude = (names: string[], name: string) =>
  names.some((n) => n.toLowerCase() === name.toLowerCase());

/** Original names of the columns the diff drops. */
const droppedNames = (s: TableDiffSpec): string[] =>
  s.columns.filter((r) => r.orig && r.dropped).map((r) => r.orig!.name);

/** True when SQLite cannot express this diff with plain ALTER TABLE actions. */
export function needsRebuild(s: TableDiffSpec, caps: DdlCaps = ddlCaps()): boolean {
  if (!caps.rebuild) return false;
  const dropped = droppedNames(s);
  for (const r of s.columns) {
    if (!r.orig) continue;
    if (r.dropped) {
      // 3.35+ drops a plain column, but refuses one that is indexed, part of a UNIQUE
      // or a foreign key, or named by a partial index / CHECK / generated expression —
      // all of which show up as a dependent naming the column.
      if (r.origPk) return true;
      if (s.dependents?.some((d) => namesInclude(d.columns, r.orig!.name))) return true;
      continue;
    }
    if (r.type.trim() && r.type.trim() !== r.orig.type) return true;
    if (r.nullable !== r.orig.nullable) return true;
    if (r.default.trim() !== r.orig.default.trim()) return true;
    if (r.isPk !== r.origPk) return true;
  }
  // A reorder is expressible ONLY as a rebuild (and only on SQLite): the new table is
  // created with the columns in the edited order.
  if (s.origOrder?.length) {
    const kept = s.columns
      .filter((r) => r.orig && !r.dropped)
      .map((r) => r.orig!.name);
    const before = s.origOrder.filter((n) => !namesInclude(dropped, n));
    if (kept.length !== before.length || kept.some((n, i) => n !== before[i])) return true;
  }
  if (s.dropConstraints.length) return true;
  if (s.addUniques?.some((u) => u.columns.length)) return true;
  if (s.addChecks?.some((c) => c.expr.trim())) return true;
  if (s.addForeignKeys?.some((f) => f.columns.length)) return true;
  return false;
}

/** Diffs the builders must refuse rather than emit. Errors block the dialog's Apply.
 *
 *  Two families:
 *  - a generated column cannot be restated by any engine's in-place ALTER (MySQL's
 *    MODIFY would drop or corrupt the expression);
 *  - a SQLite rebuild recreates the table from what Tusk can SEE, so it must refuse
 *    anything it would silently destroy or emit against a stale name. */
export function tableDiffProblems(s: TableDiffSpec, caps: DdlCaps = ddlCaps()): DdlProblem[] {
  const out: DdlProblem[] = [];
  for (const r of s.columns) {
    if (!r.orig || !r.generated?.trim() || r.dropped) continue;
    const changed =
      (r.type.trim() && r.type.trim() !== r.orig.type) ||
      r.nullable !== r.orig.nullable ||
      r.default.trim() !== r.orig.default.trim() ||
      r.comment !== r.orig.comment ||
      r.isPk !== r.origPk;
    if (changed)
      out.push({
        level: "error",
        message: `"${r.orig.name}" is a generated column (${r.generated.trim()}). ${caps.label} can't rewrite one from here — drop and re-add it, or edit it as SQL.`,
      });
  }
  if (!caps.rebuild || !needsRebuild(s, caps)) return out;

  if (s.definitionRead === false)
    out.push({
      level: "error",
      message:
        "Tusk couldn't read this table's stored CREATE statement, so a rebuild could drop CHECK constraints, collations or generated columns it never saw. Edit the table as SQL instead.",
    });

  // The rebuild replays index, constraint and trigger text captured BEFORE the edit, so
  // a rename in the same pass would replay it against names that no longer exist.
  const renamed = s.columns.filter((r) => r.orig && !r.dropped && r.name.trim() && r.name.trim() !== r.orig.name);
  const tableRenamed = !!s.newName.trim() && s.newName.trim() !== s.table;
  if (renamed.length || tableRenamed)
    out.push({
      level: "error",
      message: `${caps.label} has to rebuild the table for these changes, and the rebuild recreates the indexes, constraints and triggers as they are written today — so a ${
        tableRenamed ? "table" : "column"
      } rename can't go in the same pass. Apply the rename on its own first.`,
    });

  const dropped = droppedNames(s);
  for (const d of s.dependents ?? [])
    for (const c of d.columns)
      if (namesInclude(dropped, c))
        out.push({
          level: "error",
          message: `Column "${c}" is used by ${d.kind} "${d.name}", which the rebuild recreates unchanged. Drop ${d.name} too (tick it above) to drop the column.`,
        });
  return out;
}

/** Drop one existing constraint, per engine. Returns [] where the engine has no
 *  constraint ALTER at all (DuckDB, SQLite — the latter goes through a rebuild). */
function dropConstraintStatements(q: string, name: string, kind: string | undefined, caps: DdlCaps): string[] {
  if (caps.dropConstraint === "none") return [];
  if (caps.dropConstraint === "typed") {
    switch (kind) {
      case "primary_key":
        return [`ALTER TABLE ${q} DROP PRIMARY KEY`];
      case "foreign_key":
        return [`ALTER TABLE ${q} DROP FOREIGN KEY ${ident(name)}`];
      case "unique":
        return [`ALTER TABLE ${q} DROP INDEX ${ident(name)}`];
      case "check":
        return [`ALTER TABLE ${q} DROP CHECK ${ident(name)}`];
      default:
        return [`ALTER TABLE ${q} DROP CONSTRAINT ${ident(name)}`];
    }
  }
  return [`ALTER TABLE ${q} DROP CONSTRAINT ${ident(name)}`];
}

/** Minimal ALTER script turning the original table into the edited state.
 *  Column type/null/default/comment changes run by original name; column renames
 *  and the table rename run last so earlier statements still resolve.
 *
 *  On SQLite, a diff the engine cannot express with ALTER TABLE is emitted as the
 *  documented table rebuild instead (see `rebuildTable`). */
export function tableDiff(s: TableDiffSpec): string {
  const caps = ddlCaps();
  if (caps.rebuild && needsRebuild(s, caps)) {
    return rebuildTable({
      schema: s.schema,
      table: s.table,
      newName: s.newName,
      columns: s.columns
        .filter((r) => !r.dropped && r.name.trim() && (r.type.trim() || r.orig))
        .map((r) => ({
          source: r.orig?.name ?? null,
          spec: { ...specOf(r), primaryKey: r.isPk },
        })),
      uniques: s.addUniques,
      checks: s.addChecks,
      foreignKeys: s.addForeignKeys,
      constraintClauses: s.keepConstraints,
      indexes: s.keepIndexes,
      triggers: s.keepTriggers,
      tableOptions: s.tableOptions,
    });
  }

  const q = qualify(s.schema, s.table);
  const stmts: string[] = [];
  const renames: string[] = [];

  for (const r of s.columns) {
    if (!r.orig || r.dropped) continue;
    const on = r.orig.name;
    const typeChanged = !!r.type.trim() && r.type.trim() !== r.orig.type;
    const nullChanged = r.nullable !== r.orig.nullable;
    const defaultChanged = r.default.trim() !== r.orig.default.trim();
    const commentChanged = r.comment !== r.orig.comment;

    if (caps.changeType === "modify") {
      // MySQL: one MODIFY rewrites the whole definition, so anything it carries
      // (type, nullability, default, AUTO_INCREMENT, comment) must be restated.
      if (typeChanged || nullChanged || commentChanged) {
        stmts.push(`ALTER TABLE ${q} MODIFY COLUMN ${columnDef({ ...specOf(r), name: on }, caps, false)}`);
      } else if (defaultChanged) {
        stmts.push(
          `ALTER TABLE ${q} ALTER COLUMN ${ident(on)} ${r.default.trim() ? `SET DEFAULT ${r.default.trim()}` : "DROP DEFAULT"}`,
        );
      }
    } else {
      if (typeChanged) stmts.push(`ALTER TABLE ${q} ALTER COLUMN ${ident(on)} TYPE ${r.type.trim()}`);
      if (nullChanged)
        stmts.push(`ALTER TABLE ${q} ALTER COLUMN ${ident(on)} ${r.nullable ? "DROP" : "SET"} NOT NULL`);
      if (defaultChanged)
        stmts.push(
          `ALTER TABLE ${q} ALTER COLUMN ${ident(on)} ${r.default.trim() ? `SET DEFAULT ${r.default.trim()}` : "DROP DEFAULT"}`,
        );
      if (commentChanged && caps.comments === "standard")
        stmts.push(`COMMENT ON COLUMN ${q}.${ident(on)} IS ${r.comment.trim() === "" ? "NULL" : commentLit(r.comment, caps)}`);
    }
    if (r.name.trim() && r.name.trim() !== on)
      renames.push(`ALTER TABLE ${q} RENAME COLUMN ${ident(on)} TO ${ident(r.name.trim())}`);
  }
  stmts.push(...renames);

  // Indexes and constraints go BEFORE the column drops: an engine refuses to drop a
  // column an index still covers, so the two only work in this order.
  for (const ix of s.dropIndexes) stmts.push(dropIndex(s.schema, ix, false, s.table));
  for (const c of s.dropConstraints)
    stmts.push(...dropConstraintStatements(q, c, s.constraintKinds?.[c], caps));

  for (const r of s.columns) if (r.orig && r.dropped) stmts.push(`ALTER TABLE ${q} DROP COLUMN ${ident(r.orig.name)}`);

  for (const r of s.columns) {
    if (r.orig || r.dropped || !r.name.trim() || !r.type.trim()) continue;
    stmts.push(...addColumnStatements(q, { ...specOf(r), comment: undefined }, caps));
    if (r.comment.trim()) {
      if (caps.comments === "standard")
        stmts.push(`COMMENT ON COLUMN ${q}.${ident(r.name.trim())} IS ${commentLit(r.comment, caps)}`);
      else if (caps.comments === "inline")
        stmts.push(`ALTER TABLE ${q} MODIFY COLUMN ${columnDef(specOf(r), caps, false)}`);
    }
  }

  const origPk = s.columns.filter((r) => r.origPk && r.orig).map((r) => r.orig!.name);
  const newPk = s.columns.filter((r) => !r.dropped && r.isPk && r.name.trim()).map((r) => r.name.trim());
  if (origPk.join("") !== newPk.join("") && caps.addPrimaryKey) {
    if (origPk.length) {
      if (caps.dropConstraint === "typed") stmts.push(`ALTER TABLE ${q} DROP PRIMARY KEY`);
      else if (s.pkName && caps.dropConstraint === "constraint")
        stmts.push(`ALTER TABLE ${q} DROP CONSTRAINT ${ident(s.pkName)}`);
    }
    if (newPk.length) stmts.push(`ALTER TABLE ${q} ADD PRIMARY KEY (${newPk.map(ident).join(", ")})`);
  }

  if (caps.addConstraint) {
    for (const u of s.addUniques ?? [])
      if (u.columns.length) stmts.push(addUnique(s.schema, s.table, u.columns, u.name));
    for (const c of s.addChecks ?? []) if (c.expr.trim()) stmts.push(addCheck(s.schema, s.table, c.expr, c.name));
    for (const f of s.addForeignKeys ?? [])
      if (f.columns.length && f.refTable && f.refColumns.length) stmts.push(addForeignKey(s.schema, s.table, f));
  }

  if (s.newComment !== s.origComment) {
    if (caps.comments === "standard")
      stmts.push(`COMMENT ON TABLE ${q} IS ${s.newComment.trim() === "" ? "NULL" : commentLit(s.newComment, caps)}`);
    else if (caps.comments === "inline")
      stmts.push(`ALTER TABLE ${q} COMMENT = ${mysqlTextLiteral(s.newComment)}`);
  }
  if (s.newSchema && caps.setSchema && s.newSchema !== s.schema)
    stmts.push(`ALTER TABLE ${q} SET SCHEMA ${ident(s.newSchema)}`);
  if (s.newName.trim() && s.newName.trim() !== s.table)
    stmts.push(renameRelation("table", s.newSchema && caps.setSchema ? s.newSchema : s.schema, s.table, s.newName.trim()));

  return stmts.join(";\n");
}

// --- DROP / TRUNCATE --------------------------------------------------------

const RELATION_KEYWORD: Record<string, string> = {
  table: "TABLE",
  view: "VIEW",
  matview: "MATERIALIZED VIEW",
};

const cascadeSuffix = (cascade: boolean, caps: DdlCaps = ddlCaps()) => (cascade && caps.cascade ? " CASCADE" : "");

export function dropRelation(kind: string, schema: string, name: string, cascade: boolean): string {
  const caps = ddlCaps();
  const q = caps.schemas ? qualify(schema, name) : ident(name);
  return `DROP ${RELATION_KEYWORD[kind] ?? "TABLE"} ${q}${cascadeSuffix(cascade, caps)}`;
}

/** DROP SCHEMA. On an engine with no schema layer (MySQL) a schema IS a database, so
 *  this emits the honest `DROP DATABASE` — the Explorer labels and guards it as one. */
export function dropSchema(name: string, cascade: boolean): string {
  const caps = ddlCaps();
  if (caps.dropSchema === "database") return dropDatabase(name);
  return `DROP SCHEMA ${ident(name)}${cascadeSuffix(cascade, caps)}`;
}

/** DROP DATABASE — must run as a single statement (cannot be in a transaction). */
export function dropDatabase(name: string): string {
  return `DROP DATABASE ${ident(name)}`;
}

/** DROP INDEX. MySQL needs the owning table (`DROP INDEX i ON t`). */
export function dropIndex(schema: string, name: string, cascade: boolean, table?: string): string {
  const caps = ddlCaps();
  if (caps.dropIndexNeedsTable)
    return `DROP INDEX ${ident(name)} ON ${table ? qualify(schema, table) : ident(schema)}`;
  const q = caps.schemas ? qualify(schema, name) : ident(name);
  return `DROP INDEX ${q}${cascadeSuffix(cascade, caps)}`;
}

export function dropSequence(schema: string, name: string, cascade: boolean): string {
  return `DROP SEQUENCE ${qualify(schema, name)}${cascadeSuffix(cascade)}`;
}

/** DROP FUNCTION by name (best-effort; errors if overloaded — needs arg types then). */
export function dropFunction(schema: string, name: string, cascade: boolean): string {
  return `DROP FUNCTION ${qualify(schema, name)}${cascadeSuffix(cascade)}`;
}

export function dropConstraint(schema: string, table: string, name: string, cascade: boolean, kind?: string): string {
  const caps = ddlCaps();
  const q = qualify(schema, table);
  if (caps.dropConstraint === "typed") return dropConstraintStatements(q, name, kind, caps)[0];
  return `ALTER TABLE ${q} DROP CONSTRAINT ${ident(name)}${cascadeSuffix(cascade, caps)}`;
}

export function dropTrigger(schema: string, table: string, name: string, cascade: boolean): string {
  const caps = ddlCaps();
  if (caps.dialect === "mysql") return `DROP TRIGGER ${qualify(schema, name)}`;
  if (caps.dialect === "sqlite") return `DROP TRIGGER ${ident(name)}`;
  return `DROP TRIGGER ${ident(name)} ON ${qualify(schema, table)}${cascadeSuffix(cascade, caps)}`;
}

export function truncate(
  schema: string,
  name: string,
  o: { cascade: boolean; restartIdentity: boolean },
): string {
  const caps = ddlCaps();
  const q = caps.schemas ? qualify(schema, name) : ident(name);
  // SQLite has no TRUNCATE; an unqualified DELETE is its documented equivalent
  // (and hits the truncate optimizer).
  if (!caps.truncate) return `DELETE FROM ${q}`;
  let s = `TRUNCATE TABLE ${q}`;
  if (!caps.truncateOptions) return s;
  if (o.restartIdentity) s += " RESTART IDENTITY";
  if (o.cascade) s += " CASCADE";
  return s;
}

// --- RENAME -----------------------------------------------------------------

export function renameRelation(kind: string, schema: string, name: string, newName: string): string {
  const caps = ddlCaps();
  const kw = kind === "view" ? "VIEW" : kind === "matview" ? "MATERIALIZED VIEW" : "TABLE";
  const q = caps.schemas ? qualify(schema, name) : ident(name);
  // MySQL renames with RENAME TABLE — the documented form, which also moves a
  // relation between databases and is the ONLY way to rename a view there
  // (MySQL has no `ALTER VIEW … RENAME TO`).
  if (caps.renameTableForm === "rename-table")
    return `RENAME TABLE ${q} TO ${qualify(schema, newName)}`;
  return `ALTER ${kw} ${q} RENAME TO ${ident(newName)}`;
}
export function renameColumn(schema: string, table: string, name: string, newName: string): string {
  const caps = ddlCaps();
  const q = caps.schemas ? qualify(schema, table) : ident(table);
  return `ALTER TABLE ${q} RENAME COLUMN ${ident(name)} TO ${ident(newName)}`;
}
export function renameSchema(name: string, newName: string): string {
  return `ALTER SCHEMA ${ident(name)} RENAME TO ${ident(newName)}`;
}
export function renameIndex(schema: string, name: string, newName: string, table?: string): string {
  const caps = ddlCaps();
  if (caps.dialect === "mysql")
    return `ALTER TABLE ${table ? qualify(schema, table) : ident(schema)} RENAME INDEX ${ident(name)} TO ${ident(newName)}`;
  return `ALTER INDEX ${qualify(schema, name)} RENAME TO ${ident(newName)}`;
}
export function renameConstraint(schema: string, table: string, name: string, newName: string): string {
  return `ALTER TABLE ${qualify(schema, table)} RENAME CONSTRAINT ${ident(name)} TO ${ident(newName)}`;
}
export function renameSequence(schema: string, name: string, newName: string): string {
  return `ALTER SEQUENCE ${qualify(schema, name)} RENAME TO ${ident(newName)}`;
}

/** PostgreSQL only: move a table to another schema. */
export function setTableSchema(schema: string, name: string, newSchema: string): string {
  return `ALTER TABLE ${qualify(schema, name)} SET SCHEMA ${ident(newSchema)}`;
}

// --- DUPLICATE --------------------------------------------------------------

/** Copy a table's structure (LIKE … INCLUDING ALL — defaults/constraints/indexes,
 *  but NOT foreign keys referencing it or triggers), optionally with data. */
export function duplicateTable(schema: string, name: string, newName: string, withData: boolean): string {
  const caps = ddlCaps();
  const src = caps.schemas ? qualify(schema, name) : ident(name);
  const dst = caps.schemas ? qualify(schema, newName) : ident(newName);
  // DuckDB/SQLite have no `LIKE … INCLUDING ALL` — use CTAS (structure-only via
  // `LIMIT 0` / `WHERE 0`). CTAS copies columns/types but not PK/indexes/defaults.
  if (caps.duplicate === "ctas") return `CREATE TABLE ${dst} AS SELECT * FROM ${src}${withData ? "" : " LIMIT 0"}`;
  // MySQL's LIKE takes no INCLUDING clause and copies indexes but not data.
  const create =
    caps.dialect === "mysql" ? `CREATE TABLE ${dst} LIKE ${src}` : `CREATE TABLE ${dst} (LIKE ${src} INCLUDING ALL)`;
  return withData ? `${create};\nINSERT INTO ${dst} SELECT * FROM ${src}` : create;
}

// --- INDEX / CONSTRAINT -----------------------------------------------------

export type IndexSpec = {
  schema: string;
  table: string;
  name?: string;
  unique: boolean;
  method: string;
  columns: string[];
  where?: string;
  ifNotExists?: boolean;
};
export function createIndex(ix: IndexSpec): string {
  const caps = ddlCaps();
  const u = ix.unique ? "UNIQUE " : "";
  const ine = ix.ifNotExists && caps.ifNotExists ? "IF NOT EXISTS " : "";
  const nm = ix.name && ix.name.trim() ? `${ident(ix.name.trim())} ` : "";
  // Only Postgres exposes the access method here; DuckDB has a single (ART) index
  // type, SQLite has one B-tree, and MySQL puts `USING` in a different position.
  const m = caps.indexMethod && ix.method && ix.method !== "btree" ? ` USING ${ix.method}` : "";
  const w = caps.partialIndex && ix.where && ix.where.trim() ? ` WHERE ${ix.where.trim()}` : "";
  const q = caps.indexTableQualified ? qualify(ix.schema, ix.table) : ident(ix.table);
  return `CREATE ${u}INDEX ${ine}${nm}ON ${q}${m} (${ix.columns.map(ident).join(", ")})${w}`;
}

export function addPrimaryKey(schema: string, table: string, cols: string[], name?: string): string {
  const caps = ddlCaps();
  // DuckDB accepts `ADD PRIMARY KEY (…)` but not a named `ADD CONSTRAINT`.
  const n = caps.addConstraint ? named(name) : "";
  return `ALTER TABLE ${qualify(schema, table)} ADD ${n}PRIMARY KEY (${cols.map(ident).join(", ")})`;
}
export function addUnique(schema: string, table: string, cols: string[], name?: string): string {
  return `ALTER TABLE ${qualify(schema, table)} ADD ${named(name)}UNIQUE (${cols.map(ident).join(", ")})`;
}
export function addCheck(schema: string, table: string, expr: string, name?: string): string {
  return `ALTER TABLE ${qualify(schema, table)} ADD ${named(name)}CHECK (${expr.trim()})`;
}
export function addForeignKey(schema: string, table: string, fk: FkSpec): string {
  return `ALTER TABLE ${qualify(schema, table)} ADD ${named(fk.name)}${fkClause(fk, ddlCaps())}`;
}

// --- SCHEMA / DATABASE ------------------------------------------------------

export function createSchema(name: string, authorization?: string): string {
  // DuckDB/MySQL have no AUTHORIZATION clause.
  const pg = ddlCaps().dialect === "postgres";
  const a = pg && authorization && authorization.trim() ? ` AUTHORIZATION ${ident(authorization.trim())}` : "";
  return `CREATE SCHEMA ${ident(name)}${a}`;
}
export function createDatabase(name: string, owner?: string, encoding?: string): string {
  const caps = ddlCaps();
  if (caps.dialect === "mysql") {
    const charset = encoding && encoding.trim() ? ` DEFAULT CHARACTER SET ${encoding.trim()}` : "";
    return `CREATE DATABASE ${ident(name)}${charset}`;
  }
  const opts: string[] = [];
  if (owner && owner.trim()) opts.push(`OWNER ${ident(owner.trim())}`);
  if (encoding && encoding.trim()) opts.push(`ENCODING ${lit(encoding.trim())}`);
  return `CREATE DATABASE ${ident(name)}${opts.length ? " WITH " + opts.join(" ") : ""}`;
}

// --- COMMENT ----------------------------------------------------------------

/** target e.g. `TABLE "public"."users"` or `COLUMN "public"."users"."id"`. */
export function comment(target: string, text: string | null): string {
  return `COMMENT ON ${target} IS ${text === null || text === "" ? "NULL" : lit(text)}`;
}

/** MySQL comments are table/column options, not statements: a table comment is an
 *  ALTER option and a column comment requires restating the column definition. */
export function commentOnTable(schema: string, table: string, text: string | null): string {
  const caps = ddlCaps();
  if (caps.comments === "inline") return `ALTER TABLE ${qualify(schema, table)} COMMENT = ${mysqlTextLiteral(text ?? "")}`;
  return comment(`TABLE ${qualify(schema, table)}`, text);
}
export function commentOnColumn(schema: string, table: string, col: ColumnSpec, text: string | null): string {
  const caps = ddlCaps();
  if (caps.comments === "inline")
    return `ALTER TABLE ${qualify(schema, table)} MODIFY COLUMN ${columnDef({ ...col, comment: text ?? "" }, caps, false)}`;
  return comment(`COLUMN ${qualify(schema, table)}.${ident(col.name)}`, text);
}

// --- MATVIEW / SEQUENCE actions ---------------------------------------------

export function refreshMatview(schema: string, name: string, concurrently: boolean): string {
  return `REFRESH MATERIALIZED VIEW ${concurrently ? "CONCURRENTLY " : ""}${qualify(schema, name)}`;
}
export function alterSequenceRestart(schema: string, name: string, value: string): string {
  return `ALTER SEQUENCE ${qualify(schema, name)} RESTART${value.trim() ? ` WITH ${value.trim()}` : ""}`;
}

// --- validation -------------------------------------------------------------

export type DdlProblem = { level: "error" | "warning"; message: string };

/** One column row as the dialogs model it. `primaryKey` is the CreateTable spelling and
 *  `isPk` the ModifyTable one — both are read, so the nullable-PK check runs from both
 *  dialogs (it silently never ran from Modify before). */
export type ValidatedColumn = {
  name: string;
  type: string;
  nullable: boolean;
  primaryKey?: boolean;
  isPk?: boolean;
  dropped?: boolean;
  default?: string;
  check?: string;
  comment?: string;
  unique?: boolean;
  identity?: boolean;
};

/** A never-touched trailing row in the Create-table builder: no name and nothing else
 *  filled in. `createTable` drops these from the emitted SQL, so validation must ignore
 *  them too — otherwise the dialog opens already reporting "Every column needs a name."
 *  and blanks its own preview. */
export function isPlaceholderColumn(c: ValidatedColumn): boolean {
  return (
    !c.name.trim() &&
    !(c.default ?? "").trim() &&
    !(c.check ?? "").trim() &&
    !(c.comment ?? "").trim() &&
    !c.primaryKey &&
    !c.isPk &&
    !c.unique &&
    !c.identity
  );
}

/** Shared column-list validation for the create/modify dialogs. Errors block the run;
 *  warnings are advisory. Identifiers are always quoted on the way out, so the only
 *  name rules that matter are "not empty" and "not a duplicate" — case-insensitively
 *  where two names differing in case are the same column to the engine. */
export function validateColumns(cols: ValidatedColumn[], caps: DdlCaps = ddlCaps()): DdlProblem[] {
  const out: DdlProblem[] = [];
  const live = cols.filter((c) => !c.dropped);
  const seen = new Map<string, string>();
  for (const c of live) {
    const name = c.name.trim();
    if (!name) {
      out.push({ level: "error", message: "Every column needs a name." });
      continue;
    }
    const key = caps.foldsCase ? name.toLowerCase() : name;
    const prior = seen.get(key);
    if (prior !== undefined) {
      out.push({
        level: "error",
        message:
          prior === name
            ? `Duplicate column name "${name}".`
            : `Column names "${prior}" and "${name}" collide (${caps.label} compares identifiers case-insensitively).`,
      });
    } else seen.set(key, name);
    if (!c.type.trim()) out.push({ level: "error", message: `Column "${name}" needs a type.` });
    if ((c.primaryKey ?? c.isPk) && c.nullable && !caps.nullablePrimaryKey)
      out.push({ level: "error", message: `Primary-key column "${name}" cannot be nullable.` });
  }
  if (!live.length) out.push({ level: "error", message: "A table needs at least one column." });
  return out;
}

/** Human note for the SQL preview: how the script will be executed. */
export function scriptNote(sql: string, caps: DdlCaps = ddlCaps()): string {
  const multi = sql.split("\n").some((l) => l.trim().endsWith(";")) || sql.includes(";\n");
  if (!multi) return "";
  return caps.transactionalDdl
    ? "Runs as one transaction — if any statement fails, nothing is applied."
    : `${caps.label} commits each DDL statement as it runs: a failure part-way leaves the earlier statements applied.`;
}

// --- GENERATE statement scaffolds -------------------------------------------

// Query scaffolds drop the schema prefix when it matches the console's active
// schema (search_path) — see qualifyIn.
/**
 * `SELECT <cols> FROM <relation>` capped at `limit` rows, in the engine's own form.
 * T-SQL has no `LIMIT`, and its `OFFSET … FETCH` requires an `ORDER BY`, so SQL Server
 * gets `SELECT TOP (n)` — the only row cap that stands on its own. Everyone else keeps
 * the trailing `LIMIT`. Quoting comes from the dialect in force, so call this inside
 * `withDialect(kind, …)` when building for a non-active connection.
 */
export function limitedSelect(cols: string, relation: string, limit: number): string {
  if (sqlDialect() === "mssql") return `SELECT TOP (${limit}) ${cols}\nFROM ${relation}`;
  return `SELECT ${cols}\nFROM ${relation}\nLIMIT ${limit}`;
}

export function genSelect(schema: string, table: string, cols: string[], activeSchema?: string | null): string {
  const c = cols.length ? cols.map(ident).join(", ") : "*";
  return limitedSelect(c, qualifyIn(schema, table, activeSchema), 100);
}
export function genInsert(schema: string, table: string, cols: string[], activeSchema?: string | null): string {
  const names = cols.length ? cols : ["column"];
  return `INSERT INTO ${qualifyIn(schema, table, activeSchema)} (${names.map(ident).join(", ")})\nVALUES (${names
    .map(() => "NULL")
    .join(", ")})`;
}
export function genUpdate(
  schema: string,
  table: string,
  cols: string[],
  pkCols: string[],
  activeSchema?: string | null,
): string {
  const sets = (cols.length ? cols : ["column"]).map((c) => `${ident(c)} = NULL`).join(",\n  ");
  const keys = pkCols.length ? pkCols : cols.slice(0, 1);
  const where = (keys.length ? keys : ["id"]).map((c) => `${ident(c)} = NULL`).join(" AND ");
  return `UPDATE ${qualifyIn(schema, table, activeSchema)} SET\n  ${sets}\nWHERE ${where}`;
}
