//! Object DDL reconstruction (for "Copy DDL"). pg_dump-style assembly from
//! `pg_catalog`. User-supplied schema/name are bound as query parameters; the
//! resolved OID (a trusted integer) is reused in the detail queries.
//!
//! Out of scope (degrade gracefully, not silently wrong): partitioning,
//! inheritance, RLS, triggers, storage params, tablespaces, collations.

use crate::db::{collect_rows, ident, AppError};
use tokio_postgres::Client;

async fn query(client: &Client, sql: &str) -> Result<Vec<Vec<Option<String>>>, AppError> {
    Ok(collect_rows(&client.simple_query(sql).await?).1)
}

fn cell(r: &[Option<String>], i: usize) -> String {
    r.get(i).and_then(|v| v.clone()).unwrap_or_default()
}

/// Quote a string literal (standard_conforming_strings assumed on).
fn lit(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

fn qual(schema: &str, name: &str) -> String {
    format!("{}.{}", ident(schema), ident(name))
}

pub async fn object_ddl(
    client: &Client,
    kind: &str,
    schema: &str,
    name: &str,
) -> Result<String, AppError> {
    match kind {
        "table" => table_ddl(client, schema, name).await,
        "view" => view_ddl(client, schema, name, false).await,
        "matview" => view_ddl(client, schema, name, true).await,
        "sequence" => sequence_ddl(client, schema, name).await,
        "function" => function_ddl(client, schema, name).await,
        other => Err(AppError::new(format!("Copy DDL not supported for {other}"))),
    }
}

async fn rel_oid(client: &Client, schema: &str, name: &str) -> Result<u32, AppError> {
    let rows = client
        .query(
            "SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace \
             WHERE n.nspname=$1 AND c.relname=$2",
            &[&schema, &name],
        )
        .await?;
    let row = rows.first().ok_or_else(|| AppError::new("relation not found"))?;
    row.try_get::<_, u32>(0)
        .map_err(|e| AppError::new(format!("unexpected catalog shape: {e}")))
}

async fn table_ddl(client: &Client, schema: &str, name: &str) -> Result<String, AppError> {
    let oid = rel_oid(client, schema, name).await?;
    let q = qual(schema, name);

    // Columns: type + identity/generated/default + NOT NULL (mutually exclusive tail).
    // Booleans are NOT cast to ::text ('true'/'false') — the text protocol returns
    // 't'/'f' for a bare bool, which the `== "t"` checks below expect. (`attidentity`
    // / `attgenerated` are "char", kept as ::text to render the readable letter.)
    let col_rows = query(client, &format!(
        "SELECT a.attname, format_type(a.atttypid,a.atttypmod), a.attnotnull, a.atthasdef, \
         pg_get_expr(d.adbin,d.adrelid), a.attidentity::text, a.attgenerated::text \
         FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum \
         WHERE a.attrelid={oid} AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum")).await?;

    let mut lines: Vec<String> = Vec::new();
    for r in &col_rows {
        let cname = cell(r, 0);
        let typ = cell(r, 1);
        let notnull = cell(r, 2) == "t";
        let hasdef = cell(r, 3) == "t";
        let defexpr = r.get(4).and_then(|v| v.clone());
        let identity = cell(r, 5); // '' | 'a' (ALWAYS) | 'd' (BY DEFAULT)
        let generated = cell(r, 6); // '' | 's' (STORED)
        let mut line = format!("    {} {}", ident(&cname), typ);
        if identity == "a" {
            line.push_str(" GENERATED ALWAYS AS IDENTITY");
        } else if identity == "d" {
            line.push_str(" GENERATED BY DEFAULT AS IDENTITY");
        } else if generated == "s" {
            if let Some(e) = &defexpr {
                line.push_str(&format!(" GENERATED ALWAYS AS ({e}) STORED"));
            }
        } else if hasdef {
            if let Some(e) = &defexpr {
                line.push_str(&format!(" DEFAULT {e}"));
            }
        }
        // Identity implies NOT NULL — pg_dump omits the explicit clause there.
        if notnull && identity.is_empty() {
            line.push_str(" NOT NULL");
        }
        lines.push(line);
    }

    // Constraints: PK/unique/check inline; FKs deferred to trailing ALTERs.
    let con_rows = query(client, &format!(
        "SELECT con.conname, con.contype::text, pg_get_constraintdef(con.oid, true) \
         FROM pg_constraint con WHERE con.conrelid={oid} ORDER BY con.contype DESC, con.conname")).await?;
    let mut fks: Vec<(String, String)> = Vec::new();
    for r in &con_rows {
        let cn = cell(r, 0);
        let ct = cell(r, 1);
        let def = cell(r, 2);
        match ct.as_str() {
            "f" => fks.push((cn, def)),
            "p" | "u" | "c" => lines.push(format!("    CONSTRAINT {} {}", ident(&cn), def)),
            _ => {}
        }
    }

    let mut out = format!("CREATE TABLE {q} (\n{}\n);", lines.join(",\n"));

    for (cn, def) in &fks {
        out.push_str(&format!("\nALTER TABLE {q} ADD CONSTRAINT {} {};", ident(cn), def));
    }

    // Plain indexes only — skip those backing a PK/unique/exclusion constraint.
    let idx_rows = query(client, &format!(
        "SELECT pg_get_indexdef(i.indexrelid, 0, true), (con.oid IS NOT NULL) \
         FROM pg_index i LEFT JOIN pg_constraint con ON con.conindid=i.indexrelid \
         WHERE i.indrelid={oid} ORDER BY i.indexrelid")).await?;
    for r in &idx_rows {
        let def = cell(r, 0);
        let backs = cell(r, 1) == "t";
        if !backs && !def.is_empty() {
            out.push_str(&format!("\n{def};"));
        }
    }

    // Comments.
    if let Some(c) = query(client, &format!("SELECT obj_description({oid},'pg_class')"))
        .await?
        .into_iter()
        .next()
        .and_then(|r| r.into_iter().next().flatten())
    {
        out.push_str(&format!("\nCOMMENT ON TABLE {q} IS {};", lit(&c)));
    }
    let ccoms = query(client, &format!(
        "SELECT a.attname, col_description(a.attrelid,a.attnum) FROM pg_attribute a \
         WHERE a.attrelid={oid} AND a.attnum>0 AND NOT a.attisdropped \
         AND col_description(a.attrelid,a.attnum) IS NOT NULL ORDER BY a.attnum")).await?;
    for r in &ccoms {
        out.push_str(&format!(
            "\nCOMMENT ON COLUMN {q}.{} IS {};",
            ident(&cell(r, 0)),
            lit(&cell(r, 1))
        ));
    }

    Ok(out)
}

async fn view_ddl(client: &Client, schema: &str, name: &str, mat: bool) -> Result<String, AppError> {
    let oid = rel_oid(client, schema, name).await?;
    let def = query(client, &format!("SELECT pg_get_viewdef({oid}, true)"))
        .await?
        .into_iter()
        .next()
        .and_then(|r| r.into_iter().next().flatten())
        .unwrap_or_default();
    let kw = if mat { "MATERIALIZED VIEW" } else { "VIEW" };
    Ok(format!(
        "CREATE {kw} {} AS\n{};",
        qual(schema, name),
        def.trim().trim_end_matches(';').trim()
    ))
}

async fn sequence_ddl(client: &Client, schema: &str, name: &str) -> Result<String, AppError> {
    let rows = client
        .query(
            "SELECT start_value, min_value, max_value, increment_by, cycle, cache_size \
             FROM pg_sequences WHERE schemaname=$1 AND sequencename=$2",
            &[&schema, &name],
        )
        .await?;
    let r = rows.first().ok_or_else(|| AppError::new("sequence not found"))?;
    // try_get: typed `get` panics on NULL or a type mismatch (compat servers, or a
    // pg_sequences row this role can only partially see).
    let seq_err = |e: tokio_postgres::Error| AppError::new(format!("unexpected pg_sequences shape: {e}"));
    let start: i64 = r.try_get(0).map_err(seq_err)?;
    let minv: i64 = r.try_get(1).map_err(seq_err)?;
    let maxv: i64 = r.try_get(2).map_err(seq_err)?;
    let inc: i64 = r.try_get(3).map_err(seq_err)?;
    let cycle: bool = r.try_get(4).map_err(seq_err)?;
    let cache: i64 = r.try_get(5).map_err(seq_err)?;
    Ok(format!(
        "CREATE SEQUENCE {}\n    INCREMENT BY {inc}\n    MINVALUE {minv}\n    MAXVALUE {maxv}\n    START WITH {start}\n    CACHE {cache}{};",
        qual(schema, name),
        if cycle { "\n    CYCLE" } else { "" }
    ))
}

async fn function_ddl(client: &Client, schema: &str, name: &str) -> Result<String, AppError> {
    // A function name can be overloaded — emit every match.
    let rows = client
        .query(
            "SELECT p.oid, p.prokind::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace \
             WHERE n.nspname=$1 AND p.proname=$2 ORDER BY p.oid",
            &[&schema, &name],
        )
        .await?;
    if rows.is_empty() {
        return Err(AppError::new("function not found"));
    }
    let mut out = String::new();
    for row in &rows {
        let (Ok(oid), Ok(prokind)) = (row.try_get::<_, u32>(0), row.try_get::<_, String>(1)) else {
            continue; // unexpected catalog shape (compat server) — skip, don't panic
        };
        if prokind != "f" && prokind != "p" {
            // pg_get_functiondef errors on aggregates ('a') / window funcs ('w').
            out.push_str(&format!(
                "-- {}.{}: {} not reconstructable via Copy DDL\n",
                schema,
                name,
                if prokind == "a" { "aggregate" } else { "window function" }
            ));
            continue;
        }
        let def = query(client, &format!("SELECT pg_get_functiondef({oid})"))
            .await?
            .into_iter()
            .next()
            .and_then(|r| r.into_iter().next().flatten())
            .unwrap_or_default();
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(def.trim_end());
        if !def.trim_end().ends_with(';') {
            out.push(';');
        }
    }
    Ok(out)
}
